// packages/react/src/context/PulseProvider.tsx
import { PulseContext } from "src/context/PulseContext";
import type { PulseProviderProps } from "src/types/PulseProviderProps";

/**
 * Publishes one Pulse to the tree below. It only publishes: it never starts
 * or disposes the Pulse, so start it at bootstrap.
 *
 * @example
 * ```tsx
 * <PulseProvider pulse={pulse}>
 *   <Application />
 * </PulseProvider>
 * ```
 */
export const PulseProvider = ({ pulse, children }: PulseProviderProps) => (
  <PulseContext.Provider value={pulse}>{children}</PulseContext.Provider>
);

// packages/svelte/src/context/PulseProvider.svelte
<!--
@component Publishes one Pulse to the components below. It only publishes: it
never starts or disposes the Pulse, so start it at bootstrap.
@example `<PulseProvider {pulse}><Application /></PulseProvider>`
-->
<script lang="ts">
  import type { Pulse } from "@priemskiyyy/pulse";
  import { setContext } from "svelte";
  import type { PulseProviderProps } from "../types/PulseProviderProps.js";
  import type { ReadableValue } from "../types/ReadableValue.js";
  import { PULSE_CONTEXT } from "./PulseContext.js";

  const props: PulseProviderProps = $props();

  setContext(PULSE_CONTEXT, {
    get current() {
      return props.pulse;
    },
  } satisfies ReadableValue<Pulse>);
</script>

{#if props.children}
  {@render props.children()}
{/if}
